services:
  mysql:
    image: mysql:latest
    container_name: mysql_ecommerce
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: server_side
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./config:/docker-entrypoint-initdb.d

volumes:
  db_data: